### ISSUE TITLE
Question about maven repo

### ISSUE THREAD

**Issue by michaelrice** [nerdErg/swagger4jaxrs#5]
Just curious what is being provided here:
mavenRepo "http://thog.nerderg.com:8070/nexus/content/groups/public/"

I keep getting timeouts trying to build the plugin at the office when it trys to call this repo.

Eventually it will timeout and move on, but leave lots of this on the screen:

:: problems summary ::
:::: ERRORS
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/grails/plugins/release/2.2.1/release-2.2.1-sources.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/grails/plugins/release/2.2.1/release-2.2.1-src.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/grails/plugins/release/2.2.1/release-2.2.1-javadoc.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/apache/apache/9/apache-9.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/apache/maven/maven-parent/19/maven-parent-19.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2-sources.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2-src.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2-javadoc.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/codehaus/plexus/plexus/1.0.4/plexus-1.0.4.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/codehaus/plexus/plexus-containers/1.0.3/plexus-containers-1.0.3.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.2/plexus-2.0.2.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.14/plexus-components-1.1.14.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/apache/apache/5/apache-5.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/apache/maven/maven-parent/11/maven-parent-11.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/apache/maven/maven/2.2.1/maven-2.2.1.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/apache/maven/wagon/wagon/1.0-beta-6/wagon-1.0-beta-6.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/apache/maven/wagon/wagon-providers/1.0-beta-6/wagon-providers-1.0-beta-6.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/nekohtml/xercesMinimal/1.9.6.2/xercesMinimal-1.9.6.2-sources.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/nekohtml/xercesMinimal/1.9.6.2/xercesMinimal-1.9.6.2-src.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/nekohtml/xercesMinimal/1.9.6.2/xercesMinimal-1.9.6.2-javadoc.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/grails/plugins/rest-client-builder/1.0.3/rest-client-builder-1.0.3-sources.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/grails/plugins/rest-client-builder/1.0.3/rest-client-builder-1.0.3-src.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/grails/plugins/rest-client-builder/1.0.3/rest-client-builder-1.0.3-javadoc.jar
| Downloading: javassist-3.12.1.GA.jar.sha1
:: problems summary ::
:::: ERRORS
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/sonatype/oss/oss-parent/5/oss-parent-5.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/com/wordnik/swagger-project_2.10/1.3.0/swagger-project_2.10-1.3.0.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/slf4j/slf4j-parent/1.6.3/slf4j-parent-1.6.3.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/com/fasterxml/oss-parent/4/oss-parent-4.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/codehaus/codehaus-parent/1/codehaus-parent-1.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/com/thoughtworks/paranamer/paranamer-parent/2.3/paranamer-parent-2.3.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/sonatype/oss/oss-parent/7/oss-parent-7.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/com/google/guava/guava-parent/13.0.1/guava-parent-13.0.1.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/com/thoughtworks/paranamer/paranamer-parent/2.5.2/paranamer-parent-2.5.2.jar
        Server access Error: Connection timed out url=http://thog.nerderg.com:8070/nexus/content/groups/public/org/reflections/reflections-parent/0.9.8/reflections-parent-0.9.8.jar

**Comment by aruizca** [comment]
I am sorry that is our maven repository. I would remove that reference from there.

Cheers,
